# kube-prometheus-stack values
defaultRules:
  disabled:
    KubeControllerManagerDown: true
    KubeProxyDown: true
    KubeSchedulerDown: true

prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    retention: 15d
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  service:
    type: ClusterIP

grafana:
  # Default dev password. Override via site config: overrides.monitoring.grafana.adminPassword
  adminPassword: admin
  persistence:
    enabled: true
    size: 1Gi
  service:
    type: ClusterIP

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  service:
    type: ClusterIP

kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
