controllerManager:
  manager:
    image:
      repository: ghcr.io/nebius/soperator/slurm-operator
      tag: "3.0.2"
    imagePullPolicy: IfNotPresent
certManager:
  enabled: true
kruise:
  installOperator: true
serviceMonitor:
  enabled: false
controllerManager:
  manager:
    env:
      isPrometheusCrdInstalled: "false"
