controllerManager:
  manager:
    image:
      repository: ghcr.io/nebius/soperator/slurm-operator
      tag: "3.0.2-patched"
    imagePullPolicy: Never
    env:
      isPrometheusCrdInstalled: "false"
certManager:
  enabled: true
kruise:
  installOperator: true
serviceMonitor:
  enabled: false
